### ISSUE TITLE
RFE: support env and volumeMounts in HabitatSpec

### ISSUE THREAD

**Issue by jeremymv2** [habitat-sh/habitat-operator#181]
This is a request for two enhancements:

 - [ ] It would be nice to be able to support habitat clusters with persistent disk requirements, such that `volumeMounts` could be defined and taken into account when the Deployment is created in kubernetes. This would enable users to create rings with services that mount a filesystem backed datastore allowing dependent services to query the ring for such things as the db service's ip/port.
 - [x] Additionally, being able to pass supervisor configuration via HAB_SVC_NAME environment variables to the containers would, I believe, be more straightforward and transparent then utilizing base64encoded `toml` implemented as a `Secret`. **[done in #184]**

**Comment by asymmetric** [comment]
Hi @jeremymv2!

We're investigating approaches to provide persistent storage. One approach is to use [`StatefulSets`](44) instead of Deployments, and add support for `volumeMounts` in the Habitat object. 

Another approach we're exploring is to relegate persistence to services outside the cluster: a stateful service running outside Kubernetes forming a ring with a stateless one inside it.

Your usecase is helpful in that it allows us to gauge interest and needs, so please feel free to add other details if they come to mind.

The environment variables part is easier to figure out/implement, I've added it to my to-do list!

**Comment by jeremymv2** [comment]
@asymmetric for a use-case, this is something I'd love to be able to migrate to the CRD habitat-operator approach.

https://github.com/jeremymv2/launch-chef-in-kubernetes/blob/master/chef-server-pod.yml

**Comment by jeremymv2** [comment]
@asymmetric the challenge is that my Chef Server use-case above has a mix of stateful/stateless services that all need to join a habitat ring.
