### ISSUE TITLE
Add +optional tag to optional fields

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat-operator#186]
As recommended [here](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#optional-vs-required).

**Comment by asymmetric** [comment]
We had some discussions about this being a backwards-incompatible change, but I'm not sure it is.

Mainly, the issue is with changing the type of optional fields to pointer type. Is this actually a problem? If the deserialization only happens within the controller, then a new controller would just deserialize the existing `Habitat` objects differently, with no breakage.

/cc @krnowak

**Comment by krnowak** [comment]
IIRC, the difference was that for a certain field earlier an empty string meant "use some sane default", and now an empty string means "use this empty string as a name for something", so to get the "use some sane default" we need to leave the field unspecified in the manifest.

That's very minor and may be a fringe use case, so I'm on the fence with it. But since you are already working on supporting multiple versions of the CRD because of the breaking stateful sets work, we can piggyback the optional stuff on this work.
