### ISSUE TITLE
Build fork in Makefile

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat-operator#226]
In our [Makefile](https://github.com/habitat-sh/habitat-operator/blob/f4f27e7b205d19f0bf3c1708fb6f87fcb15cba93/Makefile#L10), we currently build upstream, even on forks.

Maybe it's possible to just use `go build ./...`, but this needs to be investigated more.

**Comment by krnowak** [comment]
I'm not sure if `go build ./...` will help - we are still importing code from `github.com/habitat-sh/habitat-operator/…` in the code.

I think that the workflow should be (IMO, of course) that you get the original repo (github.com/habitat-sh/habitat-operator) and then add git remotes pointing to forks there. Nothing needs to change then.

**Comment by asymmetric** [comment]
How does this solve the problem of the version we're building/testing though?

**Comment by krnowak** [comment]
Well, that's an unusual problem to begin with - usually forks rely on CI of the upstream repo, not on their own. So if you really want to run CI also for a fork, then:

- either you use relative imports for all habitat-operator specific packages and use `go build ./cmd/habitat-operator` (or `make GITHUB_ORG=kinvolk build`). But I guess it is generally agreed that relative imports are a no-no.
- or you put code of your fork in `$GOPATH/src/habitat-sh/habitat-operator` and have no problems at all with. And you went with it in #224, right? Admittedly this need to be solved separately for every CI we want to use. And needs to be changed upstream, so forks don't have to carry their own changes to the CI file (like `.travis.yml`, not a problem in this case).

But instead of setting up CI for a fork, you can just create a WIP, DO-NOT-MERGE PR and let CI of the upstream repo handle the testing.

**Comment by asymmetric** [comment]
Closing, since we expect people to clone upstream and add their fork with `git remote add`.
